package main

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
	"unicode"
)

//go:embed templates/*.tmpl
var templateFS embed.FS

// doNotEdit is the first line of every emitted file, and the string the header guard matches.
const doNotEdit = "// Code generated by hack/gen-types. DO NOT EDIT."

// errHandWritten is returned when an output path exists and is not generated. It aborts the
// whole run rather than the one file: a partial regeneration leaves the tree in a state no
// diff explains.
var errHandWritten = errors.New("output path exists and is not generated")

// output is one file the run will write.
type output struct {
	Path string
	Body []byte
}

// emitter renders the templates and decides what reaches the disk.
type emitter struct {
	tmpl *template.Template
	root string
}

// newEmitter parses the templates once.
func newEmitter(root string) (*emitter, error) {
	funcs := template.FuncMap{"title": title}

	tmpl, err := template.New("gen-types").Funcs(funcs).ParseFS(templateFS, "templates/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("parsing the templates: %w", err)
	}

	return &emitter{tmpl: tmpl, root: root}, nil
}

// render executes one template and gofmts the result before it can reach the disk. Formatting
// in-process rather than in a separate `make fmt` step is what makes byte-identity between two
// runs achievable at all: a formatting pass that may or may not have run is not a pass.
func (e *emitter) render(name, path string, data any) (output, error) {
	var buf bytes.Buffer

	if err := e.tmpl.ExecuteTemplate(&buf, name, data); err != nil {
		return output{}, fmt.Errorf("rendering %s into %s: %w", name, path, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return output{}, fmt.Errorf("gofmt on %s: %w\n%s", path, err, numbered(buf.String()))
	}

	return output{Path: filepath.Join(e.root, path), Body: formatted}, nil
}

// guard refuses to write over a file that is not generated. Checked for every output before
// any of them is written, so a run that would clobber one hand-written file writes nothing at
// all -- forgetting to mark a kind hand-written is easier than remembering to, so this is the
// mechanism that catches the likely mistake.
func guard(outputs []output) error {
	var errs []error

	for _, out := range outputs {
		existing, err := os.ReadFile(out.Path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}

		if err != nil {
			return fmt.Errorf("reading %s: %w", out.Path, err)
		}

		if !bytes.HasPrefix(existing, []byte(doNotEdit)) {
			errs = append(errs, fmt.Errorf("%w: %s", errHandWritten, out.Path))
		}
	}

	return errors.Join(errs...)
}

// write puts every output on the disk, after the guard has cleared all of them.
func write(outputs []output) error {
	if err := guard(outputs); err != nil {
		return err
	}

	for _, out := range outputs {
		if err := os.MkdirAll(filepath.Dir(out.Path), 0o755); err != nil {
			return fmt.Errorf("creating %s: %w", filepath.Dir(out.Path), err)
		}

		if err := os.WriteFile(out.Path, out.Body, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", out.Path, err)
		}
	}

	return nil
}

// check reports the paths whose contents differ from what the run would write, comparing
// against the working tree rather than against git: a dirty tree with legitimately
// uncommitted work then reports exactly the files the emitter would change and nothing else.
func check(outputs []output) []string {
	var stale []string

	for _, out := range outputs {
		existing, err := os.ReadFile(out.Path)
		if err != nil || !bytes.Equal(existing, out.Body) {
			stale = append(stale, out.Path)
		}
	}

	slices.Sort(stale)

	return stale
}

// title upper-cases the first rune, for a spec field name used as a Go identifier.
func title(in string) string {
	if in == "" {
		return in
	}

	return string(unicode.ToUpper(rune(in[0]))) + in[1:]
}

// numbered prefixes each line with its number, so a gofmt error on generated source points at
// something a reader can find.
func numbered(in string) string {
	var out strings.Builder

	for i, line := range strings.Split(in, "\n") {
		fmt.Fprintf(&out, "%4d\t%s\n", i+1, line)
	}

	return out.String()
}
