---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups
  - netboxclusters
  - netboxclustertypes
  - netboxdeviceroles
  - netboxdevices
  - netboxdevicetypes
  - netboxinterfaces
  - netboxipaddressclaims
  - netboxipaddresses
  - netboxiprangeclaims
  - netboxipranges
  - netboxmanufacturers
  - netboxplatforms
  - netboxprefixclaims
  - netboxvirtualdisks
  - netboxvirtualmachines
  - netboxvminterfaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups/finalizers
  - netboxclusters/finalizers
  - netboxclustertypes/finalizers
  - netboxdeviceroles/finalizers
  - netboxdevices/finalizers
  - netboxdevicetypes/finalizers
  - netboxinterfaces/finalizers
  - netboxipaddressclaims/finalizers
  - netboxipaddresses/finalizers
  - netboxiprangeclaims/finalizers
  - netboxipranges/finalizers
  - netboxlocations/finalizers
  - netboxmanufacturers/finalizers
  - netboxplatforms/finalizers
  - netboxprefixclaims/finalizers
  - netboxprefixes/finalizers
  - netboxregions/finalizers
  - netboxroutetargets/finalizers
  - netboxsitegroups/finalizers
  - netboxsites/finalizers
  - netboxtags/finalizers
  - netboxtenantgroups/finalizers
  - netboxtenants/finalizers
  - netboxvirtualdisks/finalizers
  - netboxvirtualmachines/finalizers
  - netboxvlangroups/finalizers
  - netboxvlans/finalizers
  - netboxvminterfaces/finalizers
  - netboxvrfs/finalizers
  verbs:
  - update
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups/status
  - netboxclusters/status
  - netboxclustertypes/status
  - netboxdeviceroles/status
  - netboxdevices/status
  - netboxdevicetypes/status
  - netboxendpoints/status
  - netboxinterfaces/status
  - netboxipaddressclaims/status
  - netboxipaddresses/status
  - netboxiprangeclaims/status
  - netboxipranges/status
  - netboxlocations/status
  - netboxmanufacturers/status
  - netboxplatforms/status
  - netboxprefixclaims/status
  - netboxprefixes/status
  - netboxregions/status
  - netboxroutetargets/status
  - netboxsitegroups/status
  - netboxsites/status
  - netboxsweeps/status
  - netboxtags/status
  - netboxtenantgroups/status
  - netboxtenants/status
  - netboxvirtualdisks/status
  - netboxvirtualmachines/status
  - netboxvlangroups/status
  - netboxvlans/status
  - netboxvminterfaces/status
  - netboxvrfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxendpoints
  - netboxrefgrants
  - netboxsweeps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxlocations
  - netboxprefixes
  - netboxregions
  - netboxroutetargets
  - netboxsitegroups
  - netboxsites
  - netboxtags
  - netboxtenantgroups
  - netboxtenants
  - netboxvlangroups
  - netboxvlans
  - netboxvrfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
