---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups
  - netboxclusters
  - netboxclustertypes
  - netboxdevices
  - netboxinterfaces
  - netboxipaddresses
  - netboxlocations
  - netboxprefixes
  - netboxregions
  - netboxroutetargets
  - netboxsitegroups
  - netboxsites
  - netboxtags
  - netboxtenantgroups
  - netboxtenants
  - netboxvlangroups
  - netboxvlans
  - netboxvrfs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups/finalizers
  - netboxclusters/finalizers
  - netboxclustertypes/finalizers
  - netboxdevices/finalizers
  - netboxinterfaces/finalizers
  - netboxipaddresses/finalizers
  - netboxlocations/finalizers
  - netboxprefixes/finalizers
  - netboxregions/finalizers
  - netboxroutetargets/finalizers
  - netboxsitegroups/finalizers
  - netboxsites/finalizers
  - netboxtags/finalizers
  - netboxtenantgroups/finalizers
  - netboxtenants/finalizers
  - netboxvlangroups/finalizers
  - netboxvlans/finalizers
  - netboxvrfs/finalizers
  verbs:
  - update
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxclustergroups/status
  - netboxclusters/status
  - netboxclustertypes/status
  - netboxdevices/status
  - netboxendpoints/status
  - netboxinterfaces/status
  - netboxipaddresses/status
  - netboxlocations/status
  - netboxprefixes/status
  - netboxregions/status
  - netboxroutetargets/status
  - netboxsitegroups/status
  - netboxsites/status
  - netboxtags/status
  - netboxtenantgroups/status
  - netboxtenants/status
  - netboxvlangroups/status
  - netboxvlans/status
  - netboxvrfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - netbox.kubeforge.org
  resources:
  - netboxendpoints
  - netboxrefgrants
  verbs:
  - get
  - list
  - watch
