#!/usr/bin/env bash
#
# Concatenates every generated CRD into one applyable file on stdout. `make crd-bundle`
# writes it to dist/, and .github/workflows/release.yaml attaches it to the GitHub release.
#
# This exists because the CRDs stopped travelling inside the Helm chart (#265, #268): Helm 3
# stores the whole chart in the release Secret and 2.7 MB of CRDs put that Secret over the
# API server's 1 MiB cap, so every install failed. Somebody installing the published OCI
# chart therefore has no crds/ to extract and no checkout to run `make install-crds` from --
# one URL they can `kubectl apply --server-side -f` is what replaces it.
#
# One file rather than a tarball of 64, because the whole point is that it is the argument
# to a single command. Not committed, for the reason it was removed from the chart: a third
# 2.7 MB copy of config/crd/bases in the tree is the copy that goes stale.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

version=$(sed -n 's/^version: *//p' "$root/charts/netbox-operator/Chart.yaml")
if [ -z "$version" ]; then
  echo "crd-bundle: no version in charts/netbox-operator/Chart.yaml" >&2
  exit 1
fi

shopt -s nullglob
sources=("$root"/config/crd/bases/*.yaml)
if [ "${#sources[@]}" -eq 0 ]; then
  echo "crd-bundle: config/crd/bases is empty. Run 'make manifests' first." >&2
  exit 1
fi

cat <<HEADER
# netbox-operator $version -- every CustomResourceDefinition, in one file.
#
# Generated by hack/crd-bundle.sh from config/crd/bases. Apply it before installing or
# upgrading the chart, and apply it server-side:
#
#   kubectl apply --server-side --force-conflicts -f netbox-operator-crds-$version.yaml
#
# Server-side because these CRDs are large enough that the last-applied-configuration
# annotation a client-side apply stores inside each object is a problem in its own right.
#
# Deleting a CRD deletes every CR of that kind, and their finalizers would then delete the
# NetBox objects those CRs describe -- so nothing here is ever removed on an uninstall.
# docs/install.md.
HEADER

# controller-gen already opens every file with its own `---`, so the separator is the
# source's and this only labels it. Emitting a second one would put each Source comment in a
# document of its own -- valid, ignored by kubectl, and confusing to read.
for src in "${sources[@]}"; do
  if [ "$(head -n 1 "$src")" != "---" ]; then
    echo "crd-bundle: $src does not start with a --- separator, so concatenating it would" >&2
    echo "crd-bundle: merge it into the previous document. controller-gen's output shape" >&2
    echo "crd-bundle: must have changed." >&2
    exit 1
  fi
  echo "---"
  echo "# Source: config/crd/bases/$(basename "$src")"
  tail -n +2 "$src"
done
