#!/usr/bin/env bash
#
# Generates the operator's Secret grant from config/rbac/credential-namespaces/namespaces.txt:
# a Role and RoleBinding per listed namespace, and the namespace list the manager reads to
# build its Secret informers. Run by `make manifests`; `make verify` fails if the output is
# not committed.
#
# The two outputs have to agree or the operator is broken in one of two ways: a namespace
# with a Role but no informer is a Secret the operator may read and never looks at, and a
# namespace with an informer but no Role is a cluster-wide `Forbidden` at startup. That is
# why one file generates both. See docs/operations/rbac.md and NBO-072.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
dir=$root/config/rbac/credential-namespaces
list=$dir/namespaces.txt
env_var=NETBOX_CREDENTIAL_NAMESPACES
role=endpoint-credential-reader

# The operator's deployed identity, read from the manifests that define it rather than
# restated here: the RoleBindings live outside config/base and so are not touched by its
# namePrefix and namespace transformers, which means they must name the transformed result.
kustomization=$root/config/base/kustomization.yaml
prefix=$(sed -n 's/^namePrefix: *//p' "$kustomization")
operator_ns=$(sed -n 's/^namespace: *//p' "$kustomization")
sa=$prefix$(sed -n 's/^  name: *//p' "$root/config/rbac/service_account.yaml" | head -1)

if [ -z "$prefix" ] || [ -z "$operator_ns" ] || [ "$sa" = "$prefix" ]; then
  echo "credential-rbac: cannot read the operator's identity from $kustomization" >&2
  exit 1
fi

# Comments and blank lines out, whitespace out, duplicates out, sorted so the output is a
# function of the set of namespaces rather than of the order somebody typed them in.
namespaces=$(sed -e 's/#.*//' -e 's/[[:space:]]//g' "$list" | grep -v '^$' | sort -u || true)

if [ -z "$namespaces" ]; then
  echo "credential-rbac: $list lists no namespaces, so the operator could not read any" >&2
  echo "credential-rbac: credential Secret. Add the namespaces holding your endpoints'" >&2
  echo "credential-rbac: token Secrets, one per line. See docs/operations/rbac.md." >&2
  exit 1
fi
if printf '%s\n' "$namespaces" | grep -qx '\*'; then
  echo "credential-rbac: '*' is not a namespace. Reading Secrets cluster-wide needs a" >&2
  echo "credential-rbac: cluster-wide grant this repository does not ship; see" >&2
  echo "credential-rbac: docs/operations/rbac.md." >&2
  exit 1
fi

banner="# Generated by hack/credential-rbac.sh from namespaces.txt. DO NOT EDIT."

{
  echo "$banner"
  echo "#"
  echo "# One Role per namespace holding endpoint credential Secrets, replacing the"
  echo "# cluster-wide 'secrets' rule the generated ClusterRole used to carry (NBO-072)."
  echo "#"
  echo "# All three verbs are load-bearing. The informer LISTs a namespace and then WATCHes"
  echo "# it, and RBAC evaluates a namespaced watch against the Role in that namespace, so"
  echo "# 'watch' here is what makes a rotated token take effect without a restart. 'get' is"
  echo "# not issued in normal operation -- reads are served from the informer -- and is kept"
  echo "# because it is strictly weaker than 'list' and it is the verb"
  echo "# 'kubectl auth can-i get secrets -n <ns>' asks about."
  while read -r namespace; do
    cat <<YAML
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $prefix$role
  namespace: $namespace
  labels:
    app.kubernetes.io/name: netbox-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $prefix$role
  namespace: $namespace
  labels:
    app.kubernetes.io/name: netbox-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $prefix$role
subjects:
- kind: ServiceAccount
  name: $sa
  namespace: $operator_ns
YAML
  done <<<"$namespaces"
} >"$dir/rbac.yaml"

{
  echo "$banner"
  echo "#"
  echo "# The namespaces the manager builds Secret informers for. It must match the Roles in"
  echo "# rbac.yaml: a cluster-scoped informer would issue a cluster-scoped LIST and WATCH,"
  echo "# which no Role can authorise, and the manager would never sync."
  echo "#"
  echo "# The Deployment is named before config/base's namePrefix and namespace"
  echo "# transformers, which is how kustomize matches a component's patch to it."
  cat <<YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: $env_var
          value: $(printf '%s' "$namespaces" | paste -sd, -)
YAML
} >"$dir/manager_env_patch.yaml"
