#!/usr/bin/env bash
#
# Generates the parts of charts/netbox-operator/ that are copies of config/: the CRDs and
# the manager ClusterRole's rules. Run by `make manifests`; `make verify` fails if the
# output is not committed.
#
# The alternative -- hand-maintaining 22 CRDs and a rule list that grows with every kind --
# is wrong within one release, and wrong in the direction that matters: a ClusterRole the
# chart forgot to widen is a controller that cannot watch its own kind, and one the chart
# widened by hand is a privilege nobody reviewed. So both are a copy, and the copy is
# checked.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
chart=$root/charts/netbox-operator
banner="# Generated by hack/helm-sync.sh. DO NOT EDIT."

# CRDs. In crds/ rather than templates/, so `helm uninstall` leaves them alone -- deleting
# a CRD deletes every CR of that kind, and their finalizers would then delete the NetBox
# objects. The cost is that Helm never *upgrades* them either: see docs/install.md and
# `make upgrade-crds`.
rm -rf "$chart/crds"
mkdir -p "$chart/crds"
for src in "$root"/config/crd/bases/*.yaml; do
  {
    echo "$banner"
    echo "# Source: config/crd/bases/$(basename "$src")"
    cat "$src"
  } >"$chart/crds/$(basename "$src")"
done

# The manager ClusterRole. Only the rules are copied; the metadata is the chart's, because
# the name has to carry the release name and config/rbac/role.yaml's does not.
rules=$(sed -n '/^rules:/,$p' "$root/config/rbac/role.yaml")
if [ -z "$rules" ]; then
  echo "helm-sync: no rules block in config/rbac/role.yaml" >&2
  exit 1
fi

# A `secrets` rule here would undo #100 silently, so the copy refuses to carry one rather
# than trusting a reviewer to notice 200 lines of generated YAML growing by four.
if printf '%s' "$rules" | grep -q '^  - secrets$'; then
  echo "helm-sync: config/rbac/role.yaml has a cluster-wide secrets rule. The chart grants" >&2
  echo "helm-sync: Secret access per namespace (templates/credential-rbac.yaml); see" >&2
  echo "helm-sync: docs/operations/rbac.md before widening it." >&2
  exit 1
fi

cat >"$chart/templates/clusterrole.yaml" <<YAML
{{- /*
$banner
Source: config/rbac/role.yaml, which controller-gen generates from the +kubebuilder:rbac
markers. Regenerate with \`make manifests\`.

Note what is *not* here: a rule for \`secrets\`. Secret access is granted one namespace at a
time by templates/credential-rbac.yaml, from .Values.credentialNamespaces
(docs/operations/rbac.md, #100). hack/helm-sync.sh fails rather than copying one in.
*/ -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netbox-operator.fullname" . }}-manager
  labels:
    {{- include "netbox-operator.labels" . | nindent 4 }}
$rules
YAML
