#!/usr/bin/env bash
#
# Renders every RBAC object the chart produces, over both of its value files, to stdout.
# `make helm-golden` writes the result to charts/netbox-operator/ci/golden-rbac.yaml and
# `make helm-verify` fails if it is not committed.
#
# Why only RBAC and not the whole render: the question a golden file has to answer here is
# "did the operator's privileges change", and a full render buries four lines of Role in
# four hundred lines of Deployment. The cluster-wide Secret read this repository removed
# (#100) is exactly the kind of regression that hides in a big diff.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
chart=$root/charts/netbox-operator
helm=${HELM:-helm}

echo "# Generated by hack/helm-golden.sh. DO NOT EDIT -- run 'make helm-golden'."
echo "#"
echo "# Every Role, ClusterRole and binding the chart renders, over both value files. A diff"
echo "# here is a change to what the operator may do. Read it as one."

for values in "$chart/values.yaml" "$chart/ci/all-features-values.yaml"; do
  echo "#"
  echo "# ===== $(basename "$values")"
  # -s picks the RBAC templates out of the render; the ClusterRole is generated from
  # config/rbac/role.yaml, so a widened +kubebuilder:rbac marker lands here too.
  "$helm" template netbox-operator "$chart" \
    -n netbox-operator-system \
    -f "$values" \
    --api-versions monitoring.coreos.com/v1 \
    -s templates/clusterrole.yaml \
    -s templates/clusterrolebinding.yaml \
    -s templates/credential-rbac.yaml \
    -s templates/leader-election-rbac.yaml
done
