#!/usr/bin/env bash
#
# Generates the parts of charts/netbox-operator/ that are copies of config/: the manager
# ClusterRole's rules and the validating webhook's rules. Run by `make manifests`;
# `make verify` fails if the output is not committed.
#
# The alternative -- hand-maintaining a rule list that grows with every kind -- is wrong
# within one release, and wrong in the direction that matters: a ClusterRole the
# chart forgot to widen is a controller that cannot watch its own kind, and one the chart
# widened by hand is a privilege nobody reviewed. So both are a copy, and the copy is
# checked. The webhook configuration is here for the third version of the same argument:
# TestShippedWebhookConfiguration asserts failurePolicy, sideEffects and the rules' scope
# against config/webhook/manifests.yaml, and a hand-written second copy in the chart would
# be the one nothing checks.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
chart=$root/charts/netbox-operator
banner="# Generated by hack/helm-sync.sh. DO NOT EDIT."

# The CRDs are deliberately NOT copied here any more, and the chart must not grow a crds/
# directory again (#265, #268). Helm 3 stores the whole chart -- crds/ included, because
# crds/ is chart content even though it is not templated -- gzipped and base64-encoded in
# the release Secret, and the API server rejects any Secret over 1 MiB. 64 CRDs is 2.7 MB of
# YAML and 424168 bytes packaged, which put every `helm install` of this chart over that
# line before a single Pod was scheduled. Without them the package is under 20 KB, and
# `make helm-package` fails if it ever climbs back.
#
# The CRDs now travel as their own artefact: `make install-crds` from a checkout,
# `make crd-bundle` for the single applyable file the release publishes. Both server-side
# apply, which is what `make upgrade-crds` already had to do. docs/install.md has the
# sequence and templates/crds-precondition.yaml fails an install that skipped it.
if [ -e "$chart/crds" ]; then
  echo "helm-sync: $chart/crds exists. A crds/ directory inside the chart is what made" >&2
  echo "helm-sync: every helm install fail (#265): Helm stores it in the release Secret and" >&2
  echo "helm-sync: the API server caps that Secret at 1 MiB. Ship CRDs through" >&2
  echo "helm-sync: 'make install-crds' / 'make crd-bundle' instead; see docs/install.md." >&2
  exit 1
fi

# The manager ClusterRole. Only the rules are copied; the metadata is the chart's, because
# the name has to carry the release name and config/rbac/role.yaml's does not.
rules=$(sed -n '/^rules:/,$p' "$root/config/rbac/role.yaml")
if [ -z "$rules" ]; then
  echo "helm-sync: no rules block in config/rbac/role.yaml" >&2
  exit 1
fi

# A `secrets` rule here would undo #100 silently, so the copy refuses to carry one rather
# than trusting a reviewer to notice 200 lines of generated YAML growing by four.
if printf '%s' "$rules" | grep -q '^  - secrets$'; then
  echo "helm-sync: config/rbac/role.yaml has a cluster-wide secrets rule. The chart grants" >&2
  echo "helm-sync: Secret access per namespace (templates/credential-rbac.yaml); see" >&2
  echo "helm-sync: docs/operations/rbac.md before widening it." >&2
  exit 1
fi

cat >"$chart/templates/clusterrole.yaml" <<YAML
{{- /*
$banner
Source: config/rbac/role.yaml, which controller-gen generates from the +kubebuilder:rbac
markers. Regenerate with \`make manifests\`.

Note what is *not* here: a rule for \`secrets\`. Secret access is granted one namespace at a
time by templates/credential-rbac.yaml, from .Values.credentialNamespaces
(docs/operations/rbac.md, #100). hack/helm-sync.sh fails rather than copying one in.
*/ -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netbox-operator.fullname" . }}-manager
  labels:
    {{- include "netbox-operator.labels" . | nindent 4 }}
$rules
YAML

# The validating webhook configuration. Only the `webhooks:` list is copied -- the metadata
# is the chart's, because the name has to carry the release name and the CA-injection
# annotation has to name the Certificate this chart renders.
webhooks=$(sed -n '/^webhooks:/,$p' "$root/config/webhook/manifests.yaml")
if [ -z "$webhooks" ]; then
  echo "helm-sync: no webhooks block in config/webhook/manifests.yaml" >&2
  exit 1
fi

# controller-gen writes the kustomize install's Service name and namespace into
# clientConfig. The chart's are computed from the release, so they are substituted here --
# and both substitutions are checked, because a clientConfig still pointing at
# `webhook-service.system.svc` is a webhook the API server cannot reach, which
# failurePolicy: Ignore turns into a silent bypass rather than an error.
service_expr='{{ include "netbox-operator.webhookServiceName" . }}'
namespace_expr='{{ .Release.Namespace }}'
webhooks=$(printf '%s\n' "$webhooks" \
  | sed -e "s|^      name: webhook-service\$|      name: $service_expr|" \
        -e "s|^      namespace: system\$|      namespace: $namespace_expr|")

if ! printf '%s' "$webhooks" | grep -qF "$service_expr"; then
  echo "helm-sync: clientConfig.service in config/webhook/manifests.yaml no longer names" >&2
  echo "helm-sync: webhook-service in namespace system, so the chart's copy would point at" >&2
  echo "helm-sync: a Service that does not exist. Update the substitution above." >&2
  exit 1
fi
if ! printf '%s' "$webhooks" | grep -qF "$namespace_expr"; then
  echo "helm-sync: clientConfig.service in config/webhook/manifests.yaml no longer names" >&2
  echo "helm-sync: namespace system, so the chart's copy would point outside the release." >&2
  exit 1
fi

cat >"$chart/templates/webhook.yaml" <<YAML
{{- if include "netbox-operator.webhookEnabled" . }}
{{- /*
$banner
Source: config/webhook/manifests.yaml, which controller-gen generates from the
+kubebuilder:webhook marker in internal/webhook/admission. Regenerate with \`make manifests\`.

One path matching \`resources: ["*"]\` inside this API group, so adding a Kind changes nothing
here -- and no \`status\` subresource in the rules, so a controller's own status write does not
pass back through admission. failurePolicy: Ignore is a decision, not an oversight; both it
and the reasoning are in docs/operations/admission-webhooks.md and asserted by
TestShippedWebhookConfiguration, which is why none of it is a chart value.

The caBundle is filled in by cert-manager's CA injector from the Certificate this chart
renders. Absent that annotation the API server would have no CA for the Service and every
review would fail its TLS handshake -- silently, under Ignore.
*/ -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "netbox-operator.fullname" . }}-validating-webhook
  labels:
    {{- include "netbox-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "netbox-operator.webhookCertName" . }}
$webhooks
{{- end }}
YAML
