apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- netbox_v1alpha1_netboxendpoint.yaml
- netbox_v1alpha1_netboxregion.yaml
- netbox_v1alpha1_netboxtag.yaml
- netbox_v1alpha1_netboxsite.yaml
- netbox_v1alpha1_netboxsitegroup.yaml
- netbox_v1alpha1_netboxlocation.yaml
- netbox_v1alpha1_netboxprefix.yaml
- netbox_v1alpha1_netboxrefgrant.yaml
- netbox_v1alpha1_netboxtenantgroup.yaml
- netbox_v1alpha1_netboxtenant.yaml
- netbox_v1alpha1_netboxroutetarget.yaml
- netbox_v1alpha1_netboxvrf.yaml
- netbox_v1alpha1_netboxvlangroup.yaml
- netbox_v1alpha1_netboxvlan.yaml
- netbox_v1alpha1_netboxclustertype.yaml
- netbox_v1alpha1_netboxclustergroup.yaml
- netbox_v1alpha1_netboxcluster.yaml
- netbox_v1alpha1_netboxvirtualmachine.yaml
- netbox_v1alpha1_netboxvminterface.yaml
- netbox_v1alpha1_netboxvirtualdisk.yaml
