//go:build !ignore_autogenerated

/*
Copyright 2026 Ricardo Molendijk.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FHRPGroupRef) DeepCopyInto(out *FHRPGroupRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FHRPGroupRef.
func (in *FHRPGroupRef) DeepCopy() *FHRPGroupRef {
	if in == nil {
		return nil
	}
	out := new(FHRPGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAssignment) DeepCopyInto(out *IPAssignment) {
	*out = *in
	if in.InterfaceRef != nil {
		in, out := &in.InterfaceRef, &out.InterfaceRef
		*out = new(InterfaceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.VMInterfaceRef != nil {
		in, out := &in.VMInterfaceRef, &out.VMInterfaceRef
		*out = new(VMInterfaceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.FHRPGroupRef != nil {
		in, out := &in.FHRPGroupRef, &out.FHRPGroupRef
		*out = new(FHRPGroupRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAssignment.
func (in *IPAssignment) DeepCopy() *IPAssignment {
	if in == nil {
		return nil
	}
	out := new(IPAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceRef) DeepCopyInto(out *InterfaceRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceRef.
func (in *InterfaceRef) DeepCopy() *InterfaceRef {
	if in == nil {
		return nil
	}
	out := new(InterfaceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationRef) DeepCopyInto(out *LocationRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationRef.
func (in *LocationRef) DeepCopy() *LocationRef {
	if in == nil {
		return nil
	}
	out := new(LocationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedBy) DeepCopyInto(out *ManagedBy) {
	*out = *in
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedBy.
func (in *ManagedBy) DeepCopy() *ManagedBy {
	if in == nil {
		return nil
	}
	out := new(ManagedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedByStatus) DeepCopyInto(out *ManagedByStatus) {
	*out = *in
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedByStatus.
func (in *ManagedByStatus) DeepCopy() *ManagedByStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedByStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxEndpoint) DeepCopyInto(out *NetBoxEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxEndpoint.
func (in *NetBoxEndpoint) DeepCopy() *NetBoxEndpoint {
	if in == nil {
		return nil
	}
	out := new(NetBoxEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxEndpointList) DeepCopyInto(out *NetBoxEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxEndpointList.
func (in *NetBoxEndpointList) DeepCopy() *NetBoxEndpointList {
	if in == nil {
		return nil
	}
	out := new(NetBoxEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxEndpointSpec) DeepCopyInto(out *NetBoxEndpointSpec) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Timeout = in.Timeout
	out.ResyncPeriod = in.ResyncPeriod
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimit)
		**out = **in
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(ManagedBy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxEndpointSpec.
func (in *NetBoxEndpointSpec) DeepCopy() *NetBoxEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxEndpointStatus) DeepCopyInto(out *NetBoxEndpointStatus) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(ManagedByStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxEndpointStatus.
func (in *NetBoxEndpointStatus) DeepCopy() *NetBoxEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(NetBoxEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxLocation) DeepCopyInto(out *NetBoxLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxLocation.
func (in *NetBoxLocation) DeepCopy() *NetBoxLocation {
	if in == nil {
		return nil
	}
	out := new(NetBoxLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxLocationList) DeepCopyInto(out *NetBoxLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxLocationList.
func (in *NetBoxLocationList) DeepCopy() *NetBoxLocationList {
	if in == nil {
		return nil
	}
	out := new(NetBoxLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxLocationSpec) DeepCopyInto(out *NetBoxLocationSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	in.SiteRef.DeepCopyInto(&out.SiteRef)
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(LocationRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxLocationSpec.
func (in *NetBoxLocationSpec) DeepCopy() *NetBoxLocationSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxObjectSpec) DeepCopyInto(out *NetBoxObjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxObjectSpec.
func (in *NetBoxObjectSpec) DeepCopy() *NetBoxObjectSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxObjectStatus) DeepCopyInto(out *NetBoxObjectStatus) {
	*out = *in
	if in.NaturalKey != nil {
		in, out := &in.NaturalKey, &out.NaturalKey
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Provenance != nil {
		in, out := &in.Provenance, &out.Provenance
		*out = new(ProvenanceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DeferredPending != nil {
		in, out := &in.DeferredPending, &out.DeferredPending
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxObjectStatus.
func (in *NetBoxObjectStatus) DeepCopy() *NetBoxObjectStatus {
	if in == nil {
		return nil
	}
	out := new(NetBoxObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxPrefix) DeepCopyInto(out *NetBoxPrefix) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxPrefix.
func (in *NetBoxPrefix) DeepCopy() *NetBoxPrefix {
	if in == nil {
		return nil
	}
	out := new(NetBoxPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxPrefix) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxPrefixList) DeepCopyInto(out *NetBoxPrefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxPrefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxPrefixList.
func (in *NetBoxPrefixList) DeepCopy() *NetBoxPrefixList {
	if in == nil {
		return nil
	}
	out := new(NetBoxPrefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxPrefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxPrefixSpec) DeepCopyInto(out *NetBoxPrefixSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(ScopeRef)
		(*in).DeepCopyInto(*out)
	}
	if in.VRFRef != nil {
		in, out := &in.VRFRef, &out.VRFRef
		*out = new(VRFRef)
		(*in).DeepCopyInto(*out)
	}
	if in.VLANRef != nil {
		in, out := &in.VLANRef, &out.VLANRef
		*out = new(VLANRef)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleRef != nil {
		in, out := &in.RoleRef, &out.RoleRef
		*out = new(RoleRef)
		(*in).DeepCopyInto(*out)
	}
	if in.IsPool != nil {
		in, out := &in.IsPool, &out.IsPool
		*out = new(bool)
		**out = **in
	}
	if in.MarkUtilized != nil {
		in, out := &in.MarkUtilized, &out.MarkUtilized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxPrefixSpec.
func (in *NetBoxPrefixSpec) DeepCopy() *NetBoxPrefixSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxPrefixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRefGrant) DeepCopyInto(out *NetBoxRefGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRefGrant.
func (in *NetBoxRefGrant) DeepCopy() *NetBoxRefGrant {
	if in == nil {
		return nil
	}
	out := new(NetBoxRefGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxRefGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRefGrantList) DeepCopyInto(out *NetBoxRefGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxRefGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRefGrantList.
func (in *NetBoxRefGrantList) DeepCopy() *NetBoxRefGrantList {
	if in == nil {
		return nil
	}
	out := new(NetBoxRefGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxRefGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRefGrantSpec) DeepCopyInto(out *NetBoxRefGrantSpec) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]RefGrantFrom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]RefGrantTo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRefGrantSpec.
func (in *NetBoxRefGrantSpec) DeepCopy() *NetBoxRefGrantSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxRefGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRegion) DeepCopyInto(out *NetBoxRegion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRegion.
func (in *NetBoxRegion) DeepCopy() *NetBoxRegion {
	if in == nil {
		return nil
	}
	out := new(NetBoxRegion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxRegion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRegionList) DeepCopyInto(out *NetBoxRegionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxRegion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRegionList.
func (in *NetBoxRegionList) DeepCopy() *NetBoxRegionList {
	if in == nil {
		return nil
	}
	out := new(NetBoxRegionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxRegionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxRegionSpec) DeepCopyInto(out *NetBoxRegionSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(RegionRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxRegionSpec.
func (in *NetBoxRegionSpec) DeepCopy() *NetBoxRegionSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxRegionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSite) DeepCopyInto(out *NetBoxSite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSite.
func (in *NetBoxSite) DeepCopy() *NetBoxSite {
	if in == nil {
		return nil
	}
	out := new(NetBoxSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxSite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSiteGroup) DeepCopyInto(out *NetBoxSiteGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSiteGroup.
func (in *NetBoxSiteGroup) DeepCopy() *NetBoxSiteGroup {
	if in == nil {
		return nil
	}
	out := new(NetBoxSiteGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxSiteGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSiteGroupList) DeepCopyInto(out *NetBoxSiteGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxSiteGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSiteGroupList.
func (in *NetBoxSiteGroupList) DeepCopy() *NetBoxSiteGroupList {
	if in == nil {
		return nil
	}
	out := new(NetBoxSiteGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxSiteGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSiteGroupSpec) DeepCopyInto(out *NetBoxSiteGroupSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(SiteGroupRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSiteGroupSpec.
func (in *NetBoxSiteGroupSpec) DeepCopy() *NetBoxSiteGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxSiteGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSiteList) DeepCopyInto(out *NetBoxSiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxSite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSiteList.
func (in *NetBoxSiteList) DeepCopy() *NetBoxSiteList {
	if in == nil {
		return nil
	}
	out := new(NetBoxSiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxSiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxSiteSpec) DeepCopyInto(out *NetBoxSiteSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxSiteSpec.
func (in *NetBoxSiteSpec) DeepCopy() *NetBoxSiteSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxSiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTag) DeepCopyInto(out *NetBoxTag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTag.
func (in *NetBoxTag) DeepCopy() *NetBoxTag {
	if in == nil {
		return nil
	}
	out := new(NetBoxTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTagList) DeepCopyInto(out *NetBoxTagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTagList.
func (in *NetBoxTagList) DeepCopy() *NetBoxTagList {
	if in == nil {
		return nil
	}
	out := new(NetBoxTagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTagSpec) DeepCopyInto(out *NetBoxTagSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.ObjectTypes != nil {
		in, out := &in.ObjectTypes, &out.ObjectTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTagSpec.
func (in *NetBoxTagSpec) DeepCopy() *NetBoxTagSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxTagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenant) DeepCopyInto(out *NetBoxTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenant.
func (in *NetBoxTenant) DeepCopy() *NetBoxTenant {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenantGroup) DeepCopyInto(out *NetBoxTenantGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenantGroup.
func (in *NetBoxTenantGroup) DeepCopy() *NetBoxTenantGroup {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenantGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTenantGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenantGroupList) DeepCopyInto(out *NetBoxTenantGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxTenantGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenantGroupList.
func (in *NetBoxTenantGroupList) DeepCopy() *NetBoxTenantGroupList {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenantGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTenantGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenantGroupSpec) DeepCopyInto(out *NetBoxTenantGroupSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(TenantGroupRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenantGroupSpec.
func (in *NetBoxTenantGroupSpec) DeepCopy() *NetBoxTenantGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenantGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenantList) DeepCopyInto(out *NetBoxTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetBoxTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenantList.
func (in *NetBoxTenantList) DeepCopy() *NetBoxTenantList {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetBoxTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetBoxTenantSpec) DeepCopyInto(out *NetBoxTenantSpec) {
	*out = *in
	out.NetBoxObjectSpec = in.NetBoxObjectSpec
	if in.GroupRef != nil {
		in, out := &in.GroupRef, &out.GroupRef
		*out = new(TenantGroupRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetBoxTenantSpec.
func (in *NetBoxTenantSpec) DeepCopy() *NetBoxTenantSpec {
	if in == nil {
		return nil
	}
	out := new(NetBoxTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvenanceStatus) DeepCopyInto(out *ProvenanceStatus) {
	*out = *in
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvenanceStatus.
func (in *ProvenanceStatus) DeepCopy() *ProvenanceStatus {
	if in == nil {
		return nil
	}
	out := new(ProvenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit) DeepCopyInto(out *RateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit.
func (in *RateLimit) DeepCopy() *RateLimit {
	if in == nil {
		return nil
	}
	out := new(RateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefGrantFrom) DeepCopyInto(out *RefGrantFrom) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefGrantFrom.
func (in *RefGrantFrom) DeepCopy() *RefGrantFrom {
	if in == nil {
		return nil
	}
	out := new(RefGrantFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefGrantTo) DeepCopyInto(out *RefGrantTo) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefGrantTo.
func (in *RefGrantTo) DeepCopy() *RefGrantTo {
	if in == nil {
		return nil
	}
	out := new(RefGrantTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionRef) DeepCopyInto(out *RegionRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionRef.
func (in *RegionRef) DeepCopy() *RegionRef {
	if in == nil {
		return nil
	}
	out := new(RegionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleRef) DeepCopyInto(out *RoleRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleRef.
func (in *RoleRef) DeepCopy() *RoleRef {
	if in == nil {
		return nil
	}
	out := new(RoleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeRef) DeepCopyInto(out *ScopeRef) {
	*out = *in
	if in.RegionRef != nil {
		in, out := &in.RegionRef, &out.RegionRef
		*out = new(RegionRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SiteGroupRef != nil {
		in, out := &in.SiteGroupRef, &out.SiteGroupRef
		*out = new(SiteGroupRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SiteRef != nil {
		in, out := &in.SiteRef, &out.SiteRef
		*out = new(SiteRef)
		(*in).DeepCopyInto(*out)
	}
	if in.LocationRef != nil {
		in, out := &in.LocationRef, &out.LocationRef
		*out = new(LocationRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeRef.
func (in *ScopeRef) DeepCopy() *ScopeRef {
	if in == nil {
		return nil
	}
	out := new(ScopeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteGroupRef) DeepCopyInto(out *SiteGroupRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteGroupRef.
func (in *SiteGroupRef) DeepCopy() *SiteGroupRef {
	if in == nil {
		return nil
	}
	out := new(SiteGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteRef) DeepCopyInto(out *SiteRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteRef.
func (in *SiteRef) DeepCopy() *SiteRef {
	if in == nil {
		return nil
	}
	out := new(SiteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRef) DeepCopyInto(out *TagRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRef.
func (in *TagRef) DeepCopy() *TagRef {
	if in == nil {
		return nil
	}
	out := new(TagRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGroupRef) DeepCopyInto(out *TenantGroupRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGroupRef.
func (in *TenantGroupRef) DeepCopy() *TenantGroupRef {
	if in == nil {
		return nil
	}
	out := new(TenantGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantRef) DeepCopyInto(out *TenantRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantRef.
func (in *TenantRef) DeepCopy() *TenantRef {
	if in == nil {
		return nil
	}
	out := new(TenantRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANRef) DeepCopyInto(out *VLANRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANRef.
func (in *VLANRef) DeepCopy() *VLANRef {
	if in == nil {
		return nil
	}
	out := new(VLANRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMInterfaceRef) DeepCopyInto(out *VMInterfaceRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMInterfaceRef.
func (in *VMInterfaceRef) DeepCopy() *VMInterfaceRef {
	if in == nil {
		return nil
	}
	out := new(VMInterfaceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFRef) DeepCopyInto(out *VRFRef) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFRef.
func (in *VRFRef) DeepCopy() *VRFRef {
	if in == nil {
		return nil
	}
	out := new(VRFRef)
	in.DeepCopyInto(out)
	return out
}
