apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/netbox.populator.io_netboxendpoints.yaml
- bases/netbox.populator.io_netboxregions.yaml
- bases/netbox.populator.io_netboxtags.yaml
- bases/netbox.populator.io_netboxsites.yaml
