apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/netbox.kubeforge.org_netboxendpoints.yaml
- bases/netbox.kubeforge.org_netboxregions.yaml
- bases/netbox.kubeforge.org_netboxtags.yaml
- bases/netbox.kubeforge.org_netboxsites.yaml
- bases/netbox.kubeforge.org_netboxsitegroups.yaml
- bases/netbox.kubeforge.org_netboxlocations.yaml
- bases/netbox.kubeforge.org_netboxprefixes.yaml
- bases/netbox.kubeforge.org_netboxrefgrants.yaml
- bases/netbox.kubeforge.org_netboxtenantgroups.yaml
- bases/netbox.kubeforge.org_netboxtenants.yaml
- bases/netbox.kubeforge.org_netboxroutetargets.yaml
- bases/netbox.kubeforge.org_netboxvrfs.yaml
- bases/netbox.kubeforge.org_netboxvlangroups.yaml
- bases/netbox.kubeforge.org_netboxvlans.yaml
