apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/netbox.kubeforge.org_netboxendpoints.yaml
- bases/netbox.kubeforge.org_netboxregions.yaml
- bases/netbox.kubeforge.org_netboxtags.yaml
- bases/netbox.kubeforge.org_netboxsites.yaml
- bases/netbox.kubeforge.org_netboxsitegroups.yaml
- bases/netbox.kubeforge.org_netboxlocations.yaml
- bases/netbox.kubeforge.org_netboxprefixes.yaml
- bases/netbox.kubeforge.org_netboxrefgrants.yaml
- bases/netbox.kubeforge.org_netboxtenantgroups.yaml
- bases/netbox.kubeforge.org_netboxtenants.yaml
- bases/netbox.kubeforge.org_netboxroutetargets.yaml
- bases/netbox.kubeforge.org_netboxvrfs.yaml
- bases/netbox.kubeforge.org_netboxvlangroups.yaml
- bases/netbox.kubeforge.org_netboxvlans.yaml
- bases/netbox.kubeforge.org_netboxclustertypes.yaml
- bases/netbox.kubeforge.org_netboxclustergroups.yaml
- bases/netbox.kubeforge.org_netboxclusters.yaml
- bases/netbox.kubeforge.org_netboxipaddresses.yaml
- bases/netbox.kubeforge.org_netboxipaddressclaims.yaml
- bases/netbox.kubeforge.org_netboxvirtualmachines.yaml
- bases/netbox.kubeforge.org_netboxvminterfaces.yaml
- bases/netbox.kubeforge.org_netboxvirtualdisks.yaml
- bases/netbox.kubeforge.org_netboxmanufacturers.yaml
- bases/netbox.kubeforge.org_netboxdeviceroles.yaml
- bases/netbox.kubeforge.org_netboxdevicetypes.yaml
- bases/netbox.kubeforge.org_netboxplatforms.yaml
- bases/netbox.kubeforge.org_netboxdevices.yaml
- bases/netbox.kubeforge.org_netboxinterfaces.yaml
- bases/netbox.kubeforge.org_netboxsweeps.yaml
- bases/netbox.kubeforge.org_netboxipranges.yaml
- bases/netbox.kubeforge.org_netboxprefixclaims.yaml
- bases/netbox.kubeforge.org_netboxiprangeclaims.yaml
- bases/netbox.kubeforge.org_netboxcontactgroups.yaml
- bases/netbox.kubeforge.org_netboxcontactroles.yaml
- bases/netbox.kubeforge.org_netboxcontacts.yaml
- bases/netbox.kubeforge.org_netboxcontactassignments.yaml
- bases/netbox.kubeforge.org_netboxrirs.yaml
- bases/netbox.kubeforge.org_netboxaggregates.yaml
- bases/netbox.kubeforge.org_netboxasns.yaml
- bases/netbox.kubeforge.org_netboxasnranges.yaml
- bases/netbox.kubeforge.org_netboxroles.yaml
- bases/netbox.kubeforge.org_netboxfhrpgroups.yaml
- bases/netbox.kubeforge.org_netboxfhrpgroupassignments.yaml
- bases/netbox.kubeforge.org_netboxservices.yaml
- bases/netbox.kubeforge.org_netboxservicetemplates.yaml
- bases/netbox.kubeforge.org_netboxcustomfieldchoicesets.yaml
- bases/netbox.kubeforge.org_netboxcustomfields.yaml
- bases/netbox.kubeforge.org_netboxcustomlinks.yaml
- bases/netbox.kubeforge.org_netboxsavedfilters.yaml
- bases/netbox.kubeforge.org_netboxexporttemplates.yaml
- bases/netbox.kubeforge.org_netboxconfigtemplates.yaml
- bases/netbox.kubeforge.org_netboxconfigcontextprofiles.yaml
- bases/netbox.kubeforge.org_netboxconfigcontexts.yaml
- bases/netbox.kubeforge.org_netboxmacaddresses.yaml
